### PR TITLE
identical path matching before pattern matching

### PR DESCRIPTION
**Pull request by abelcastilloavant**
I tried having two routes in a toy microserver called `\raw` and `\rawer`, and the microserver could never call the `\rawer` function.

I added a couple of lines of code to try identical matching before pattern matching when determining routes.

### CODE REVIEW

**Comment by kirillseva** [comment]
nice!

**Comment by kirillseva** [comment]
Should we even have pattern matching...

**Comment by kirillseva** [comment]
@abelcastilloavant could you up version please and write some changelog stuff? will merge after that, good find!

**Comment by abelcastilloavant** [comment]
upping version number. I couldn't find a changelog, should I make one?

**Comment by peterhurford** [comment]
@abelcastilloavant Yep, create a new file `NEWS.md` that [looks like this](https://github.com/syberia/stagerunner/blob/master/NEWS.md).

**Comment by peterhurford** [comment]
Looks good to go otherwise :+1:

**Pull request merged**
